OBJS = 02_rendering_SDL.cpp

CC = g++

CFLAGS = -Wall -Werror -std=c++14 -pedantic
LDFLAGS = -lSDL2 -lSDL2_image
OBJ_NAME = 02_rendering_SDL

all: $(OBJS)
	$(CC) $(CFLAGS) $(OBJS) -o $(OBJ_NAME) $(LDFLAGS)
